import { systemWeights } from 'react-native-typography';
export default {
  disabledOpacity: 0.5,
  roundness: 6,
  colors: {
    AlmostTransparent: 'rgba(9, 14, 25, 0.5)',
    Background: 'rgb(36, 35, 35)',
    'Background Inverse (Main Font)': 'rgb(242, 242, 242)',
    'Bad/Error/Cancel': 'rgb(254, 41, 0)',
    Blue: 'rgb(59, 130, 246)',
    BlueTransparent: 'rgba(59, 130, 246, 0.2)',
    Bronze: 'rgb(143, 113, 67)',
    Community_Gray: 'rgb(238, 242, 246)',
    'Custom #007aff': 'rgb(0, 122, 255)',
    'Custom #eef2f6': 'rgb(238, 242, 246)',
    'Custom Color': 'rgb(0, 128, 0)',
    'Custom Color_2': 'rgb(255, 0, 0)',
    'Custom Color_3': 'rgb(139, 0, 0)',
    'Custom Color_4': 'rgba(128, 0, 0, 0)',
    'Custom Color_5': 'rgba(0, 0, 0, 0.3)',
    Custom_Color: 'rgb(0, 122, 255)',
    DarkOrange: 'rgb(249, 115, 22)',
    'Discord Blurple': 'rgb(88, 101, 242)',
    Divider: 'rgb(58, 56, 56)',
    Error: 'rgba(255, 69, 100, 1)',
    Fair: 'rgb(255, 154, 1)',
    Good: 'rgb(11, 187, 0)',
    Green: 'rgb(74, 222, 128)',
    GreenTransparent: 'rgba(74, 222, 128, 0.2)',
    Light: 'rgba(165, 173, 183, 1)',
    'Light Good': 'rgb(212, 237, 187)',
    'Light Inverse': 'rgba(255, 255, 255, 0.68)',
    Light_Inverse: 'rgba(255, 255, 255, 0.68)',
    Light_low_importance_text: 'rgba(165, 173, 183, 1)',
    Medium: 'rgba(70, 78, 88, 1)',
    'Medium Inverse': 'rgba(255, 255, 255, 0.87)',
    Medium_Blocks: 'rgb(58, 56, 56)',
    Medium_Inverse: 'rgba(255, 255, 255, 0.87)',
    NFT_TIME_Black: 'rgb(0, 0, 0)',
    NFT_TIME_Blue: 'rgb(33, 158, 188)',
    NFT_TIME_Border: 'rgb(153, 153, 153)',
    NFT_TIME_Cyan_White: 'rgb(233, 236, 239)',
    NFT_TIME_Dark_Gray: 'rgb(64, 72, 82)',
    NFT_TIME_Dark_White: 'rgb(241, 241, 241)',
    NFT_TIME_Divider_Dark: 'rgb(151, 151, 151)',
    NFT_TIME_Gray: 'rgb(111, 111, 111)',
    NFT_TIME_Icons: 'rgb(86, 86, 86)',
    NFT_TIME_Light_Blue: 'rgb(142, 202, 230)',
    NFT_TIME_Light_Gray: 'rgb(223, 223, 223)',
    NFT_TIME_Lime_Green: 'rgb(221, 242, 71)',
    NFT_TIME_Primary_Black: 'rgb(16, 16, 1)',
    NFT_TIME_Red: 'rgb(255, 0, 0)',
    NFT_TIME_Stone: 'rgb(207, 207, 207)',
    NFT_TIME_Stone_Gray: 'rgb(183, 183, 183)',
    NFT_Time_Dark_Mode_Link: 'rgb(252, 252, 252)',
    NFT_Time_Green: 'rgb(0, 128, 0)',
    NFT_Time_Hot_Blue: 'rgb(0, 0, 255)',
    NFT_Time_Mac_Gray: 'rgb(128, 128, 128)',
    NFT_Time_Secondary: 'rgb(71, 129, 242)',
    NFT_Time_UI_Black: 'rgb(16, 16, 16)',
    NFT_White_v2: 'rgb(255, 255, 255)',
    Not_used: 'rgb(255, 97, 0)',
    Orange: 'rgb(251, 146, 60)',
    OrangeTransparent: 'rgba(251, 146, 60, 0.2)',
    Poor: 'rgb(255, 97, 0)',
    Primary: 'rgb(191, 171, 128)',
    PrimaryDarker: 'rgb(190, 18, 60)',
    Primary_Transparent: 'rgba(168, 163, 151, 0.95)',
    Purple: 'rgb(147, 51, 234)',
    PurpleTransparent: 'rgba(147, 51, 234, 0.21)',
    Secondary: 'rgb(236, 217, 184)',
    Secondary_Transparent: 'rgba(214, 211, 206, 0.95)',
    Strong: 'rgba(18, 20, 44, 1)',
    'Strong Inverse': 'rgb(255, 255, 255)',
    Strong_Inverse: 'rgba(255, 255, 255, 1)',
    Strong_Text_on_gold_buttons: 'rgb(15, 15, 15)',
    Surface: 'rgba(255, 255, 255, 1)',
    Teal: 'rgb(45, 212, 191)',
    TealBackground: 'rgba(45, 212, 191, 0.2)',
    TextPlaceholder: 'rgb(136, 144, 153)',
    Transparent: 'rgba(0, 0, 0, 0)',
    TripItBlue: 'rgb(14, 134, 212)',
    ViewBG: 'rgba(152, 153, 156, 0.25)',
    'White SS Background': 'rgb(255, 255, 255)',
    Z_Dummy_Color: 'rgb(235, 69, 255)',
    almostTransparent: 'rgba(9, 14, 25, 0.5)',
    background: 'rgb(36, 35, 35)',
    backgroundInverseMainFont: 'rgb(242, 242, 242)',
    badErrorCancel: 'rgb(254, 41, 0)',
    blue: 'rgb(59, 130, 246)',
    blueTransparent: 'rgba(59, 130, 246, 0.2)',
    bronze: 'rgb(143, 113, 67)',
    communityGray: 'rgb(238, 242, 246)',
    custom_rgb0_122_255: 'rgb(0, 122, 255)',
    custom_rgb0_128_0: 'rgb(0, 128, 0)',
    custom_rgb139_0_0: 'rgb(139, 0, 0)',
    custom_rgb238_242_246: 'rgb(238, 242, 246)',
    custom_rgb255_0_0: 'rgb(255, 0, 0)',
    custom_rgba0_0_0_03: 'rgba(0, 0, 0, 0.3)',
    custom_rgba128_0_0_0: 'rgba(128, 0, 0, 0)',
    darkOrange: 'rgb(249, 115, 22)',
    discordBlurple: 'rgb(88, 101, 242)',
    divider: 'rgb(58, 56, 56)',
    error: 'rgba(255, 69, 100, 1)',
    fair: 'rgb(255, 154, 1)',
    good: 'rgb(11, 187, 0)',
    green: 'rgb(74, 222, 128)',
    greenTransparent: 'rgba(74, 222, 128, 0.2)',
    light: 'rgba(165, 173, 183, 1)',
    lightGood: 'rgb(212, 237, 187)',
    lightInverse: 'rgba(255, 255, 255, 0.68)',
    lightLowImportanceText: 'rgba(165, 173, 183, 1)',
    medium: 'rgba(70, 78, 88, 1)',
    mediumBlocks: 'rgb(58, 56, 56)',
    mediumInverse: 'rgba(255, 255, 255, 0.87)',
    nFTTIMEBlack: 'rgb(0, 0, 0)',
    nFTTIMEBlue: 'rgb(33, 158, 188)',
    nFTTIMEBorder: 'rgb(153, 153, 153)',
    nFTTIMECyanWhite: 'rgb(233, 236, 239)',
    nFTTIMEDarkGray: 'rgb(64, 72, 82)',
    nFTTIMEDarkWhite: 'rgb(241, 241, 241)',
    nFTTIMEDividerDark: 'rgb(151, 151, 151)',
    nFTTIMEGray: 'rgb(111, 111, 111)',
    nFTTIMEIcons: 'rgb(86, 86, 86)',
    nFTTIMELightBlue: 'rgb(142, 202, 230)',
    nFTTIMELightGray: 'rgb(223, 223, 223)',
    nFTTIMELimeGreen: 'rgb(221, 242, 71)',
    nFTTIMEPrimaryBlack: 'rgb(16, 16, 1)',
    nFTTIMERed: 'rgb(255, 0, 0)',
    nFTTIMEStone: 'rgb(207, 207, 207)',
    nFTTIMEStoneGray: 'rgb(183, 183, 183)',
    nFTTimeDarkModeLink: 'rgb(252, 252, 252)',
    nFTTimeGreen: 'rgb(0, 128, 0)',
    nFTTimeHotBlue: 'rgb(0, 0, 255)',
    nFTTimeMacGray: 'rgb(128, 128, 128)',
    nFTTimeSecondary: 'rgb(71, 129, 242)',
    nFTTimeUIBlack: 'rgb(16, 16, 16)',
    nFTWhiteV2: 'rgb(255, 255, 255)',
    notUsed: 'rgb(255, 97, 0)',
    orange: 'rgb(251, 146, 60)',
    orangeTransparent: 'rgba(251, 146, 60, 0.2)',
    poor: 'rgb(255, 97, 0)',
    primary: 'rgb(191, 171, 128)',
    primaryDarker: 'rgb(190, 18, 60)',
    primaryTransparent: 'rgba(168, 163, 151, 0.95)',
    purple: 'rgb(147, 51, 234)',
    purpleTransparent: 'rgba(147, 51, 234, 0.21)',
    secondary: 'rgb(236, 217, 184)',
    secondaryTransparent: 'rgba(214, 211, 206, 0.95)',
    strong: 'rgba(18, 20, 44, 1)',
    strongInverse: 'rgba(255, 255, 255, 1)',
    strongTextOnGoldButtons: 'rgb(15, 15, 15)',
    surface: 'rgba(255, 255, 255, 1)',
    teal: 'rgb(45, 212, 191)',
    tealBackground: 'rgba(45, 212, 191, 0.2)',
    textPlaceholder: 'rgb(136, 144, 153)',
    transparent: 'rgba(0, 0, 0, 0)',
    tripItBlue: 'rgb(14, 134, 212)',
    viewBG: 'rgba(152, 153, 156, 0.25)',
    whiteSSBackground: 'rgb(255, 255, 255)',
    zDummyColor: 'rgb(235, 69, 255)',
  },
  typography: {
    body1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    body2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    button: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 16,
    },
    caption: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    headline1: {
      ...systemWeights.bold,
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    headline2: {
      ...systemWeights.bold,
      fontSize: 48,
      letterSpacing: 0,
      lineHeight: 58,
    },
    headline3: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    headline4: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 34,
    },
    headline5: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline6: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 24,
    },
    overline: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    subtitle1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    subtitle2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom100: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom101: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom102: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom103: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom104: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom105: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom106: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom107: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom108: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom109: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom110: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom111: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom112: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom113: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom114: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom115: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom116: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom117: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom118: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom119: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom120: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom121: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom122: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom123: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom124: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom125: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom126: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom127: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom128: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom129: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom130: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom131: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom132: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom133: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom134: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom135: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom136: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom137: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom138: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom139: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom14: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 24,
    },
    custom140: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom141: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom142: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom143: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom144: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom145: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom146: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom147: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom148: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom149: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom15: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 24,
    },
    custom150: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom151: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom152: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom153: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom154: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom155: {
      ...systemWeights.bold,
      fontSize: 22,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom156: {
      ...systemWeights.bold,
      fontSize: 22,
      letterSpacing: 1,
      lineHeight: 22,
    },
    custom157: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 22,
    },
    custom158: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom159: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom16: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 20,
    },
    custom160: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom161: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom162: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom163: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom164: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom165: {
      ...systemWeights.semibold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom166: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom167: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom168: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom169: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom17: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 20,
    },
    custom170: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom171: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom172: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom173: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom174: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom175: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom176: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom177: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom178: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom179: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom18: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom180: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom181: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom182: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom183: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom184: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom185: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom186: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom187: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom188: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom189: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom19: {
      ...systemWeights.regular,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom190: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom191: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom192: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom193: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom194: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom195: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom196: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom197: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom198: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom199: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom20: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom200: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom201: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom202: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom203: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom204: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom205: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom206: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom207: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom208: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom209: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom21: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom210: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom211: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom212: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom213: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom214: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom215: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom216: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom217: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom22: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom23: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom24: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 5,
      lineHeight: 12,
    },
    custom25: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom26: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 5,
      lineHeight: 16,
    },
    custom27: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom28: {
      ...systemWeights.regular,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom29: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom30: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom31: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom32: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom33: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom34: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom35: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom36: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom37: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom38: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom39: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom40: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom41: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom42: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom43: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom44: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom45: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom46: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom47: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom48: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom49: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom50: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom51: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom52: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom53: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom54: {
      ...systemWeights.regular,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom55: {
      ...systemWeights.regular,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom56: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom57: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom58: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom59: {
      ...systemWeights.regular,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom60: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom61: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom62: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom63: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom64: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom65: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom66: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom67: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 1,
    },
    custom68: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom69: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom70: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 1,
    },
    custom71: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom72: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom73: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom74: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom75: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom76: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom77: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom78: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom79: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom80: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom81: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom82: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom83: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom84: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom85: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom86: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom87: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom88: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom89: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom90: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom91: {
      ...systemWeights.bold,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom92: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom93: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom94: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom95: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom96: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom97: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom98: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom99: {
      ...systemWeights.regular,
      fontSize: 20,
      letterSpacing: 1,
      lineHeight: 16,
    },
  },
};
