import React from 'react';

const abbrTeamName = x => {
  const teamsTable = {
    // NFL
    'Arizona Cardinals': 'ARI',
    'Atlanta Falcons': 'ATL',
    'Baltimore Ravens': 'BAL',
    'Buffalo Bills': 'BUF',
    'Carolina Panthers': 'CAR',
    'Chicago Bears': 'CHI',
    'Cincinnati Bengals': 'CIN',
    'Cleveland Browns': 'CLE',
    'Dallas Cowboys': 'DAL',
    'Denver Broncos': 'DEN',
    'Detroit Lions': 'DET',
    'Green Bay Packers': 'GB',
    'Houston Texans': 'HOU',
    'Indianapolis Colts': 'IND',
    'Jacksonville Jaguars': 'JAC',
    'Kansas City Chiefs': 'KC',
    'Las Vegas Raiders': 'LV',
    'Los Angeles Chargers': 'LAC',
    'Los Angeles Rams': 'LAR',
    'Miami Dolphins': 'MIA',
    'Minnesota Vikings': 'MIN',
    'New England Patriots': 'NE',
    'New Orleans Saints': 'NO',
    'New York Giants': 'NYG',
    'New York Jets': 'NYJ',
    'Philadelphia Eagles': 'PHI',
    'Pittsburgh Steelers': 'PIT',
    'San Francisco 49ers': 'SF',
    'Seattle Seahawks': 'SEA',
    'Tampa Bay Buccaneers': 'TB',
    'Tennessee Titans': 'TEN',
    'Washington Commanders': 'WAS',
    // NBA
    'Atlanta Hawks': 'ATL',
    'Brooklyn Nets': 'BKN',
    'Boston Celtics': 'BOS',
    'Charlotte Hornets': 'CHA',
    'Chicago Bulls': 'CHI',
    'Cleveland Cavaliers': 'CLE',
    'Dallas Mavericks': 'DAL',
    'Denver Nuggets': 'DEN',
    'Detroit Pistons': 'DET',
    'Golden State Warriors': 'GSW',
    'Houston Rockets': 'HOU',
    'Indiana Pacers': 'IND',
    'Los Angeles Clippers': 'LAC',
    'Los Angeles Lakers': 'LAL',
    'Memphis Grizzlies': 'MEM',
    'Miami Heat': 'MIA',
    'Milwaukee Bucks': 'MIL',
    'Minnesota Timberwolves': 'MIN',
    'New Orleans Pelicans': 'NOP',
    'New York Knicks': 'NYK',
    'Oklahoma City Thunder': 'OKC',
    'Orlando Magic': 'ORL',
    'Philadelphia 76ers': 'PHI',
    'Phoenix Suns': 'PHX',
    'Portland Trail Blazers': 'POR',
    'Sacramento Kings': 'SAC',
    'San Antonio Spurs': 'SAS',
    'Toronto Raptors': 'TOR',
    'Utah Jazz': 'UTA',
    'Washington Wizards': 'WAS',
    // NCAA
    'Boston College Eagles': 'Boston College',
    'Clemson Tigers': 'Clemson',
    'Duke Blue Devils': 'Duke',
    'Florida State Seminoles': 'Florida State',
    'Georgia Tech Yellow Jackets': 'Georgia Tech',
    'Louisville Cardinals': 'Louisville',
    'Miami (FL) Hurricanes': 'Miami (FL)',
    'NC State Wolfpack': 'NC State',
    'Pittsburgh Panthers': 'Pittsburgh',
    'Syracuse Orange': 'Syracuse',
    'North Carolina Tar Heels': 'North Carolina',
    'Virginia Cavaliers': 'Virginia',
    'Virginia Tech Hokies': 'Virginia Tech',
    'Wake Forest Demon Deacons': 'Wake Forest',
    'Illinois Fighting Illini': 'Illinois',
    'Indiana Hoosiers': 'Indiana',
    'Iowa Hawkeyes': 'Iowa',
    'Michigan Wolverines': 'Michigan',
    'Michigan State Spartans': 'Michigan State',
    'Minnesota Golden Gophers': 'Minnesota',
    'Nebraska Cornhuskers': 'Nebraska',
    'Northwestern Wildcats': 'Northwestern',
    'Ohio State Buckeyes': 'Ohio State',
    'Penn State Nittany Lions': 'Penn State',
    'Purdue Boilermakers': 'Purdue',
    'Rutgers Scarlet Knights': 'Rutgers',
    'Maryland Terrapins': 'Maryland',
    'Wisconsin Badgers': 'Wisconsin',
    'Baylor Bears': 'Baylor',
    'Iowa State Cyclones': 'Iowa State',
    'Kansas Jayhawks': 'Kansas',
    'Kansas State Wildcats': 'Kansas State',
    'Oklahoma Sooners': 'Oklahoma',
    'Oklahoma State Cowboys': 'Oklahoma State',
    'TCU Horned Frogs': 'TCU',
    'Texas Longhorns': 'Texas',
    'Texas Tech Red Raiders': 'Texas Tech',
    'West Virginia Mountaineers': 'West Virginia',
    'Arizona Wildcats': 'Arizona',
    'Arizona State Sun Devils': 'Arizona State',
    'California Golden Bears': 'California',
    'Colorado Buffaloes': 'Colorado',
    'Oregon Ducks': 'Oregon',
    'Oregon State Beavers': 'Oregon State',
    'Stanford Cardinal': 'Stanford',
    'UCLA Bruins': 'UCLA',
    'USC Trojans': 'USC',
    'Utah Utes': 'Utah',
    'Washington Huskies': 'Washington',
    'Washington State Cougars': 'Washington State',
    'Alabama Crimson Tide': 'Alabama',
    'Arkansas Razorbacks': 'Arkansas',
    'Auburn Tigers': 'Auburn',
    'Florida Gators': 'Florida',
    'Georgia Bulldogs': 'Georgia',
    'Kentucky Wildcats': 'Kentucky',
    'LSU Tigers': 'LSU',
    'Ole Miss Rebels': 'Ole Miss',
    'Mississippi State Bulldogs': 'Mississippi State',
    'Missouri Tigers': 'Missouri',
    'South Carolina Gamecocks': 'South Carolina',
    'Tennessee Volunteers': 'Tennessee',
    'Texas A&M Aggies': 'Texas A&M',
    'Vanderbilt Commodores': 'Vanderbilt',
    'BYU Cougars': 'BYU',
    'Army Black Knights': 'Army',
    'UMass Minutemen': 'UMass',
    'Notre Dame Fighting Irish': 'Notre Dame',
    'Cincinnati Bearcats': 'Cincinnati',
    'UConn Huskies': 'UConn',
    'ECU Pirates': 'ECU',
    'Houston Cougars': 'Houston',
    'Memphis Tigers': 'Memphis',
    'Navy Midshipmen': 'Navy',
    'SMU Mustangs': 'SMU',
    'South Florida Bulls': 'South Florida',
    'Temple Owls': 'Temple',
    'Tulane Green Wave': 'Tulane',
    'Tulsa Golden Hurricane': 'Tulsa',
    'UCF Knights': 'UCF',
    'Charlotte 49ers': 'Charlotte',
    'FAU Owls': 'FAU',
    'FIU Panthers': 'FIU',
    'Louisiana Tech Bulldogs': 'Louisiana Tech',
    'Marshall Thundering Herd': 'Marshall',
    'Middle Tennessee Blue Raiders': 'Middle Tennessee',
    'North Texas Mean Green': 'North Texas',
    'Old Dominion Monarchs': 'Old Dominion',
    'Rice Owls': 'Rice',
    'Southern Miss Golden Eagles': 'Southern Miss',
    'UTEP Miners': 'UTEP',
    'UTSA Roadrunners': 'UTSA',
    'WKU Hilltoppers': 'WKU',
    'Akron Zips': 'Akron',
    'Ball State Cardinals': 'Ball State',
    'Bowling Green Falcons': 'Bowling Green',
    'Buffalo Bulls': 'Buffalo',
    'Central Michigan Chippewas': 'Central Michigan',
    'Eastern Michigan Eagles': 'Eastern Michigan',
    'Kent State Golden Flashes': 'Kent State',
    'Miami (OH) Redhawks': 'Miami (OH)',
    'Northern Illinois Huskies': 'Northern Illinois',
    'Ohio Bobcats': 'Ohio',
    'Toledo Rockets': 'Toledo',
    'Western Michigan Broncos': 'Western Michigan',
    'Air Force Falcons': 'Air Force',
    'Boise State Broncos': 'Boise State',
    'Colorado State Rams': 'Colorado State',
    'Fresno State Bulldogs': 'Fresno State',
    'Hawaii Rainbow Warriors': 'Hawaii',
    'Nevada Wolf Pack': 'Nevada',
    'New Mexico Lobos': 'New Mexico',
    'San Diego State Aztecs': 'San Diego State',
    'San José State Spartans': 'San José State',
    'UNLV Rebels': 'UNLV',
    'Utah State Aggies': 'Utah State',
    'Wyoming Cowboys': 'Wyoming',
    'Appalachian State Mountaineers': 'Appalachian State',
    'Arkansas State Red Wolves': 'Arkansas State',
    'Georgia Southern Eagles': 'Georgia Southern',
    'Georgia State Panthers': 'Georgia State',
    'Idaho Vandals': 'Idaho',
    "Louisiana Lafayette Ragin' Cajuns": 'Louisiana Lafayette',
    'Louisiana Monroe Warhawks': 'Louisiana Monroe',
    'New Mexico State Aggies': 'New Mexico State',
    'South Alabama Jaguars': 'South Alabama',
    'Texas State Bobcats': 'Texas State',
    'Troy Trojans': 'Troy',
    'Cal Poly Mustangs': 'Cal Poly',
    'Eastern Washington Eagles': 'Eastern Washington',
    'Idaho State Bengals': 'Idaho State',
    'Montana Grizzlies': 'Montana',
    'Montana State Bobcats': 'Montana State',
    'North Dakota Fighting Hawks': 'North Dakota',
    'Northern Arizona Lumberjacks': 'Northern Arizona',
    'Northern Colorado Bears': 'Northern Colorado',
    'Portland State Vikings': 'Portland State',
    'Sacramento State Hornets': 'Sacramento State',
    'Southern Utah Thunderbirds': 'Southern Utah',
    'UC Davis Aggies': 'UC Davis',
    'Weber State Wildcats': 'Weber State',
    'Charleston Southern Buccaneers': 'Charleston Southern',
    'Coastal Carolina Chanticleers': 'Coastal Carolina',
    "Gardner-Webb Runnin' Bulldogs": 'Gardner-Webb',
    'Kennesaw State Owls': 'Kennesaw State',
    'Liberty Flames': 'Liberty',
    'Monmouth Hawks': 'Monmouth',
    'Presbyterian Blue Hose': 'Presbyterian',
    'Albany Great Danes': 'Albany',
    "Delaware Fightin' Blue Hens": 'Delaware',
    'Elon Phoenix': 'Elon',
    'James Madison Dukes': 'James Madison',
    'Maine Black Bears': 'Maine',
    'New Hampshire Wildcats': 'New Hampshire',
    'Rhode Island Rams': 'Rhode Island',
    'Richmond Spiders': 'Richmond',
    'Stony Brook Seawolves': 'Stony Brook',
    'Towson Tigers': 'Towson',
    'Villanova Wildcats': 'Villanova',
    'William & Mary Tribe': 'William & Mary',
    'Brown Bears': 'Brown',
    'Cornell Big Red': 'Cornell',
    'Columbia Lions': 'Columbia',
    'Dartmouth Big Green': 'Dartmouth',
    'Harvard Crimson': 'Harvard',
    'UPenn Quakers': 'UPenn',
    'Princeton Tigers': 'Princeton',
    'Yale Bulldogs': 'Yale',
    'Bethune-Cookman Wildcats': 'Bethune-Cookman',
    'Delaware State Hornets': 'Delaware State',
    'Florida A&M Rattlers': 'Florida A&M',
    'Hampton Pirates': 'Hampton',
    'Howard Bison': 'Howard',
    'Morgan State Bears': 'Morgan State',
    'Norfolk State Spartans': 'Norfolk State',
    'North Carolina A&T Aggies': 'North Carolina A&T',
    'NC Central Eagles': 'NC Central',
    'Savannah State Tigers': 'Savannah State',
    'South Carolina State Bulldogs': 'South Carolina State',
    'Illinois State Redbirds': 'Illinois State',
    'Indiana State Sycamores': 'Indiana State',
    'Missouri State Bears': 'Missouri State',
    'North Dakota State Bison': 'North Dakota State',
    'Northern Iowa Panthers': 'Northern Iowa',
    'South Dakota Coyotes': 'South Dakota',
    'South Dakota State Jackrabbits': 'South Dakota State',
    'Southern Illinois Salukis': 'Southern Illinois',
    'Western Illinois Leathernecks': 'Western Illinois',
    'Youngstown State Penguins': 'Youngstown State',
    'Bryant Bulldogs': 'Bryant',
    'Central Connecticut Blue Devils': 'Central Connecticut',
    'Duquesne Dukes': 'Duquesne',
    'Robert Morris (PA) Colonials': 'Robert Morris (PA)',
    'Sacred Heart Pioneers': 'Sacred Heart',
    'St. Francis (PA) Red Flash': 'St. Francis (PA)',
    'Wagner Seahawks': 'Wagner',
    'Austin Peay Governors': 'Austin Peay',
    'Eastern Illinois Panthers': 'Eastern Illinois',
    'Eastern Kentucky Colonels': 'Eastern Kentucky',
    'Jacksonville State Gamecocks': 'Jacksonville State',
    'Murray State Racers': 'Murray State',
    'Southeast Missouri Redhawks': 'Southeast Missouri',
    'Tennessee State Tigers': 'Tennessee State',
    'Tennessee Tech Golden Eagles': 'Tennessee Tech',
    'Tennessee-Martin Skyhawks': 'Tennessee-Martin',
    'Bucknell Bison': 'Bucknell',
    'Colgate Raiders': 'Colgate',
    'Fordham Rams': 'Fordham',
    'Georgetown Hoyas': 'Georgetown',
    'Holy Cross Crusaders': 'Holy Cross',
    'Lafayette Leopards': 'Lafayette',
    'Lehigh Mountain Hawks': 'Lehigh',
    'Butler Bulldogs': 'Butler',
    'Campbell Fighting Camels': 'Campbell',
    'Davidson Wildcats': 'Davidson',
    'Dayton Flyers': 'Dayton',
    'Drake Bulldogs': 'Drake',
    'Jacksonville Dolphins': 'Jacksonville',
    'Marist Red Foxes': 'Marist',
    'Morehead State Eagles': 'Morehead State',
    'San Diego Toreros': 'San Diego',
    'Stetson Hatters': 'Stetson',
    'Valparaiso Beacons': 'Valparaiso',
    'Chattanooga Mocs': 'Chattanooga',
    'ETSU Buccaneers': 'ETSU',
    'Furman Paladins': 'Furman',
    'Mercer Bears': 'Mercer',
    'Samford Bulldogs': 'Samford',
    'The Citadel Bulldogs': 'The Citadel',
    'VMI Keydets': 'VMI',
    'Western Carolina Catamounts': 'Western Carolina',
    'Wofford Terriers': 'Wofford',
    'Abilene Christian Wildcats': 'Abilene Christian',
    'Central Arkansas Bears': 'Central Arkansas',
    'Houston Baptist Huskies': 'Houston Baptist',
    'Incarnate Word Cardinals': 'Incarnate Word',
    'Lamar Cardinals': 'Lamar',
    'McNeese State Cowboys': 'McNeese State',
    'Nicholls State Colonels': 'Nicholls State',
    'Northwestern State Demons': 'Northwestern State',
    'Sam Houston State Bearkats': 'Sam Houston State',
    'Southeastern Louisiana Lions': 'Southeastern Louisiana',
    'Stephen F. Austin Lumberjacks': 'Stephen F. Austin',
    'Alabama A&M Bulldogs': 'Alabama A&M',
    'Alabama State Hornets': 'Alabama State',
    'Alcorn State Braves': 'Alcorn State',
    'Arkansas-Pine Bluff Golden Lions': 'Arkansas-Pine Bluff',
    'Grambling State Tigers': 'Grambling State',
    'Jackson State Tigers': 'Jackson State',
    'Mississippi Valley State Delta Devils': 'Mississippi Valley State',
    'Prairie View A&M Panthers': 'Prairie View A&M',
    'Southern University Jaguars': 'Southern University',
    'Texas Southern Tigers': 'Texas Southern',
    'Wichita State Shockers': 'Wichita State',
    'Winthrop Eagles': 'Winthrop',
    'Green Bay Phoenix': 'Green Bay',
    'Milwaukee Panthers': 'Milwaukee',
    'Wright State Raiders': 'Wright State',
    'Xavier Musketeers': 'Xavier',
    'Kansas City Roos': 'Kansas City',
    "Mount St. Mary's Mountaineers": "Mount St. Mary's",
    'Omaha Mavericks': 'Omaha',
    'NJIT Highlanders': 'NJIT',
    'New Orleans Privateers': 'New Orleans',
    'Niagara Purple Eagles': 'Niagara',
    'UNC Asheville Bulldogs': 'UNC Asheville',
    'UNC Greensboro Spartans': 'UNC Greensboro',
    'UNC Wilmington Seahawks': 'UNC Wilmington',
    'North Florida Ospreys': 'North Florida',
    'Northeastern Huskies': 'Northeastern',
    'Northern Kentucky Norse': 'Northern Kentucky',
    'Oakland Golden Grizzlies': 'Oakland',
    'Oral Roberts Golden Eagles': 'Oral Roberts',
    'Pacific Tigers': 'Pacific',
    'Pepperdine Waves': 'Pepperdine',
    'Portland Pilots': 'Portland',
    'Providence Friars': 'Providence',
    'Purdue Fort Wayne Mastodons': 'Purdue Fort Wayne',
    'Quinnipiac Bobcats': 'Quinnipiac',
    'Radford Highlanders': 'Radford',
    'Rider Broncs': 'Rider',
    'St. Bonaventure Bonnies': 'St. Bonaventure',
    'St. Francis Brooklyn Terriers': 'St. Francis Brooklyn',
    "St. John's Red Storm": "St. John's",
    "Saint Joseph's Hawks": "Saint Joseph's",
    'Saint Louis Billikens': 'Saint Louis',
    "Saint Mary's Gaels": "Saint Mary's",
    "Saint Peter's Peacocks": "Saint Peter's",
    'San Francisco Dons': 'San Francisco',
    'Santa Clara Broncos': 'Santa Clara',
    'Seattle Redhawks': 'Seattle',
    'Seton Hall Pirates': 'Seton Hall',
    'Siena Saints': 'Siena',
    'USC Upstate Spartans': 'USC Upstate',
    'Southern Jaguars': 'Southern',
    'SIU Edwardsville Cougars': 'SIU Edwardsville',
    'Texas A&M-Corpus Christi Islanders': 'Texas A&M-Corpus Christi',
    'UT Arlington Mavericks': 'UT Arlington',
    'UTRGV Vaqueros': 'UTRGV',
    'Utah Valley Wolverines': 'Utah Valley',
    'Vermont Catamounts': 'Vermont',
    'VCU Rams': 'VCU',
    'UAB Blazers': 'UAB',
    'American Eagles': 'American',
    'Little Rock Trojans': 'Little Rock',
    'Belmont Bruins': 'Belmont',
    'Binghamton Bearcats': 'Binghamton',
    'Boston University Terriers': 'Boston University',
    'Bradley Braves': 'Bradley',
    'UC Irvine Anteaters': 'UC Irvine',
    'UC Riverside Highlanders': 'UC Riverside',
    'UC Santa Barbara Gauchos': 'UC Santa Barbara',
    'Cal State Bakersfield Roadrunners': 'Cal State Bakersfield',
    'Cal State Fullerton Titans': 'Cal State Fullerton',
    'Long Beach State The Beach': 'Long Beach State',
    'Cal State Northridge Matadors': 'Cal State Northridge',
    'Canisius Golden Griffins': 'Canisius',
    'College of Charleston Cougars': 'College of Charleston',
    'Chicago State Cougars': 'Chicago State',
    'Cleveland State Vikings': 'Cleveland State',
    'Coppin State Eagles': 'Coppin State',
    'Creighton Bluejays': 'Creighton',
    'Denver Pioneers': 'Denver',
    'DePaul Blue Demons': 'DePaul',
    'Detroit Titans': 'Detroit',
    'Drexel Dragons': 'Drexel',
    'Evansville Purple Aces': 'Evansville',
    'Fairfield Stags': 'Fairfield',
    'Fairleigh Dickinson Knights': 'Fairleigh Dickinson',
    'FGCU Eagles': 'FGCU',
    'George Mason Patriots': 'George Mason',
    'George Washington Colonials': 'George Washington',
    'Gonzaga Bulldogs': 'Gonzaga',
    'Grand Canyon Antelopes': 'Grand Canyon',
    'Hartford Hawks': 'Hartford',
    'High Point Panthers': 'High Point',
    'Hofstra Pride': 'Hofstra',
    'UIC Flames': 'UIC',
    'IUPUI Jaguars': 'IUPUI',
    'Iona Gaels': 'Iona',
    'La Salle Explorers': 'La Salle',
    'Lipscomb Bisons': 'Lipscomb',
    'LIU Sharks': 'LIU',
    'Longwood Lancers': 'Longwood',
    'Loyola Chicago Ramblers': 'Loyola Chicago',
    'Loyola (MD) Greyhounds': 'Loyola (MD)',
    'Loyola Marymount Lions': 'Loyola Marymount',
    'Manhattan Jaspers': 'Manhattan',
    'Marquette Golden Eagles': 'Marquette',
    'UMBC Retrievers': 'UMBC',
    'Maryland Eastern Shore Hawks': 'Maryland Eastern Shore',
    'UMass Lowell River Hawks': 'UMass Lowell',
    // MLB
    'Arizona Diamondbacks': 'ARI',
    'Atlanta Braves': 'ATL',
    'Baltimore Orioles': 'BAL',
    'Boston Red Sox': 'BOS',
    'Chicago White Sox': 'CWS',
    'Chicago Cubs': 'CHC',
    'Cincinnati Reds': 'CIN',
    'Cleveland Guardians': 'CLE',
    'Colorado Rockies': 'COL',
    'Detroit Tigers': 'DET',
    'Houston Astros': 'HOU',
    'Kansas City Royals': 'KC',
    'Los Angeles Angels': 'ANA',
    'Los Angeles Dodgers': 'LA',
    'Miami Marlins': 'MIA',
    'Milwaukee Brewers': 'MIL',
    'Minnesota Twins': 'MIN',
    'New York Mets': 'NYM',
    'New York Yankees': 'NYY',
    'Oakland Athletics': 'OAK',
    'Philadelphia Phillies': 'PHI',
    'Pittsburgh Pirates': 'PIT',
    'San Diego Padres': 'SD',
    'San Francisco Giants': 'SF',
    'Seattle Mariners': 'SEA',
    'St. Louis Cardinals': 'STL',
    'Tampa Bay Rays': 'TB',
    'Texas Rangers': 'TEX',
    'Toronto Blue Jays': 'TOR',
    'Washington Nationals': 'WAS',
    // NHL
    'Anaheim Ducks': 'ANA',
    'Buffalo Sabres': 'BUF',
    'Boston Bruins': 'BOS',
    'Arizona Coyotes': 'ARI',
    'Colorado Avalanche': 'COL',
    'Chicago Blackhawks': 'CHI',
    'Dallas Stars': 'DAL',
    'Carolina Hurricanes': 'CAR',
    'Edmonton Oilers': 'EDM',
    'Minnesota Wild': 'MIN',
    'Detroit Red Wings': 'DET',
    'Columbus Blue Jackets': 'CBJ',
    'Los Angeles Kings': 'LAK',
    'New Jersey Devils': 'NJD',
    'New York Rangers': 'NYR',
    'New York Islanders': 'NYI',
    'Calgary Flames': 'CGY',
    'Ottawa Senators': 'OTT',
    'Montréal Canadiens': 'MTL',
    'Philadelphia Flyers': 'PHI',
    'Pittsburgh Penguins': 'PIT',
    'San Jose Sharks': 'SJS',
    'Florida Panthers': 'FLA',
    'Nashville Predators': 'NSH',
    'Tampa Bay Lightning': 'TBL',
    'Toronto Maple Leafs': 'TOR',
    'St Louis Blues': 'STL',
    'Vancouver Canucks': 'VAN',
    'Vegas Golden Knights': 'VGK',
    'Washington Capitals': 'WSH',
    'Winnipeg Jets': 'WPG',
    'Seattle Kraken': 'SEA',
  };

  return teamsTable[x] || x;
};

export default abbrTeamName;
